container_name: nexus
container_image: sonatype/nexus3
volume_name: nexus-data
new_admin_pw: crazypassw0rd2
proxy_repo_name: base-docker
group_repo_name: docker-group
docker_group_listening_port: 8083
docker_group_member_list: [
  "docker.io",
  "ghcr.io-proxy",
  "quay.io-proxy",
  "k8s.gcr.io"
]
proxy_repos:
  - name: "docker.io"
    url: "https://registry-1.docker.io"
    index_type: "HUB"
  - name: "ghcr.io-proxy"
    url: "https://ghcr.io"
    index_type: "REGISTRY"
  - name: "quay.io-proxy"
    url: "https://quay.io/"
    index_type: "REGISTRY"
  - name: "k8s.gcr.io"
    url: "https://k8s.gcr.io/"
    index_type: "REGISTRY"
